### ISSUE TITLE
where is com.prt2121.databinding.databinding.ActivityMainBinding?

### ISSUE THREAD

**Issue by szpnygo** [prt2121/DataBindingSample#1]
i can't find this class

**Comment by pt2121** [comment]
It's generated. You may need to clean and rebuild the project.

**Comment by szpnygo** [comment]
only android-MNC?

**Comment by pt2121** [comment]
Well, yes. It's a developer preview version (M preview) so we need 'android-MNC'. It's the same as when they launched L preview.
Anyway, eventually, other Android versions will be supported.

**Comment by szpnygo** [comment]
thank u ! hope it will soon be used in other Android versions

**Comment by pt2121** [comment]
Welcome. Thanks for checking out the project!

**Comment by janpfeil** [comment]
As stated in the data binding guide, it is a support library and can be used with api level 7+.
I set compileSdkVersion and targetSdkVersion lower than MNC and run it i.e. on api level 17.
See my changes in app/build.gradle

```
android {
    compileSdkVersion 22
    buildToolsVersion '23.0.0 rc1'
    defaultConfig {
        applicationId "com.prt2121.databinding"
        minSdkVersion 17
        targetSdkVersion 22
```

**Comment by pt2121** [comment]
@janpfeil Thanks. I'll fix it or feel free to send PR.
